/**
  * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an 'AS IS' BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
'use strict';
var log4js = require('log4js');
var logger = log4js.getLogger('connection');
logger.setLevel('DEBUG');

var path = require('path');
var util = require('util');

var hfc = require('fabric-client');
hfc.setLogger(logger);

async function getClient (userOrg, username) {
    logger.info('============ START getClient for user org %s, user %s', userOrg, username);

    // the connection profiles should be here, as generated by connection-profile/gen-connection-profile.sh
	let config = '../tmp/connection-profile/ngo-connection-profile.json';
    let clientConfig = '../tmp/connection-profile/org1/client-ngo-connection-profile-org1.json';

    logger.info('##### getClient - Loading connection profiles from file: %s and %s', config, clientConfig);

    // build a client context and load it with a connection profile
	// first load the network settings, then load the client specific settings
    let client = hfc.loadFromConfig(config);
    client.loadFromConfig(clientConfig);

	// this will create both the state store and the crypto store based
	// on the settings in the client section of the connection profile
	await client.initCredentialStores();

    // The getUserContext call tries to get the user from persistence.
	// If the user has been saved to persistence then that means the user has
	// been registered and enrolled. If the user is found in persistence
	// the call will then assign the user to the client object.
	if(username) {
		let user = await client.getUserContext(username, true);
		if(!user) {
			throw new Error(util.format('##### getClient - User was not found :', username));
		} else {
			logger.debug('##### getClient - User %s was found to be registered and enrolled', username);
		}
	}
    logger.info('============ END getClient for user org %s, user %s', userOrg, username);

	return client;
}

var getRegisteredUser = async function(username, userOrg) {
    logger.info('============ START getRegisteredUser for user %s, org %s', username, userOrg);
	try {
        let client = await getClient(userOrg);
     	// first check to see if the user is already enrolled
		var user = await client.getUserContext(username, true);
		if (user && user.isEnrolled()) {
			logger.info('##### getRegisteredUser - User %s was found in persistence store to be registered and enrolled', username);
		} else {
			// user was not enrolled, so we will need an admin user object to register
			logger.info('##### getRegisteredUser - User %s was not enrolled, so we will need an admin user object to register', username);
			var admins = hfc.getConfigSetting('admins');
			let adminUserObj = await client.setUserContext({username: admins[0].username, password: admins[0].secret});
			let caClient = client.getCertificateAuthority();
			let secret = await caClient.register({
				enrollmentID: username,
				affiliation: userOrg.toLowerCase() + '.department1'
			}, adminUserObj);
			logger.debug('##### getRegisteredUser - Successfully got the secret for user %s',username);
			user = await client.setUserContext({username:username, password:secret});
			logger.debug('##### getRegisteredUser - Successfully enrolled username %s  and setUserContext on the client object', username);
		}
		if(user && user.isEnrolled) {
            var response = {
                success: true,
                secret: user._enrollmentSecret,
                message: username + ' enrolled Successfully',
            };
            return response;
		} else {
			throw new Error('User was not enrolled ');
		}
	} catch(error) {
		logger.error('============ getRegisteredUser - Failed to get registered user: %s with error: %s', username, error.toString());
		return 'failed '+error.toString();
	}
};

var getLogger = function(moduleName) {
	var logger = log4js.getLogger(moduleName);
	logger.setLevel('DEBUG');
	return logger;
};

exports.getClient = getClient;
exports.getLogger = getLogger;
exports.getRegisteredUser = getRegisteredUser;
